### ISSUE TITLE
different shapes between `x_path_1` and `x_path_2`

### ISSUE THREAD

**Issue by XianzheMa** [wandering007/nasnet-pytorch#5]
Hi, I just run the nasnet code but get an error at [this line](https://github.com/wandering007/nasnet-pytorch/blob/627721317b6021f59ec597fcbbc2287508e56b1a/nasnet/layers.py#L137): 
```RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 7 for tensor number 1 in the list.` ```
I think `x_path_1` is one element longer than `x_path_2` along the last two dimensions, as [at the previous line](https://github.com/wandering007/nasnet-pytorch/blob/627721317b6021f59ec597fcbbc2287508e56b1a/nasnet/layers.py#L135) you stripped the first element on `x_path_2`. What do you think?

Thanks a lot for your help.

Best,
Xianzhe

**Comment by wandering007** [comment]
Thanks for your attention. The strip is needed since [path_2 avgool](https://github.com/wandering007/nasnet-pytorch/blob/627721317b6021f59ec597fcbbc2287508e56b1a/nasnet/layers.py#L213) uses the ceiling mode. It works when your input image sizes are even numbers (e.g. 224x224). Maybe you can check it in this way.

**Comment by XianzheMa** [comment]
Got it. Thanks!
